const products = [
  {
    id: 1,
    name: "Dress 1",
    type: "dress",
    buy_price: 6.0,
    sell_price: 4.99,
    discount: "17% OFF",
    stock: 12,
    status: "In Stock",
    sizes: ["73", "80", "90"],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1756114387/products/svtuq8odg8j5pchy4a4e.jpg",
  },
  {
    id: 2,
    name: "Dress 2",
    type: "dress",
    buy_price: 5.8,
    sell_price: 4.99,
    discount: "14% OFF",
    stock: 8,
    status: "In Stock",
    sizes: ["66", "73", "80", "90", "100"],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1756114570/products/rlktetaipbjcjxpf04jc.jpg",
  },
  {
    id: 3,
    name: "Dress 3",
    type: "dress",
    buy_price: 5.5,
    sell_price: 4.5,
    discount: "18% OFF",
    stock: 0,
    status: "Out of Stock",
    sizes: [],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1756114573/products/cguylkdw65gc4kmmw4c7.jpg",
  },
  {
    id: 4,
    name: "Dress 4",
    type: "dress",
    buy_price: 5.5,
    sell_price: 4.5,
    discount: "18% OFF",
    stock: 0,
    status: "Out of Stock",
    sizes: [],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1756114575/products/p4iw75qjtmnuyuoo853j.jpg",
  },
  {
    id: 5,
    name: "Dress 5",
    type: "dress",
    buy_price: 6.0,
    sell_price: 4.99,
    discount: "17% OFF",
    stock: 15,
    status: "In Stock",
    sizes: ["73", "80", "90"],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1756114580/products/gr4yi7kasemmjtkvqeqo.jpg",
  },
  {
    id: 6,
    name: "Dress 6",
    type: "dress",
    buy_price: 5.8,
    sell_price: 4.99,
    discount: "14% OFF",
    stock: 7,
    status: "In Stock",
    sizes: ["66", "73", "80", "90", "100"],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1756114584/products/ocehgsdp2i7t1s5e5udf.jpg",
  },
  {
    id: 7,
    name: "Dress 7",
    type: "dress",
    buy_price: 5.21,
    sell_price: 4.2,
    discount: "18% OFF",
    stock: 0,
    status: "Out of Stock",
    sizes: [],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1756114586/products/auzyeysfgplqg97tsix8.jpg",
  },
  {
    id: 8,
    name: "Dress 8",
    type: "dress",
    buy_price: 5.5,
    sell_price: 4.5,
    discount: "18% OFF",
    stock: 0,
    status: "Out of Stock",
    sizes: [],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1756114595/products/de6fnofsvxw74i9qnrhe.jpg",
  },
  {
    id: 9,
    name: "Dress 9",
    type: "dress",
    buy_price: 5.777,
    sell_price: 4.566767,
    discount: "18% OFF",
    stock: 6,
    status: "In Stock",
    sizes: [],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1756114597/products/jsq3filddq0kyqampgpy.jpg",
  },
  {
    id: 10,
    name: "Dress 10",
    type: "dress",
    buy_price: 7.7,
    sell_price: 4.99,
    discount: "17% OFF",
    stock: 10,
    status: "In Stock",
    sizes: ["73", "80", "90", "100"],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1756114611/products/de4rmuvzzovsr8r4him7.jpg",
  },
  {
    id: 11,
    name: "Set 1",
    type: "set",
    buy_price: 7.8,
    sell_price: 4.99,
    discount: "30% OFF",
    stock: 14,
    status: "In Stock",
    sizes: ["66", "73", "80", "90", "100"],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1756114387/products/svtuq8odg8j5pchy4a4e.jpg",
  },
  {
    id: 12,
    name: "Set 2",
    type: "set",
    buy_price: 9.8,
    sell_price: 4.5,
    discount: "18% OFF",
    stock: 0,
    status: "Out of Stock",
    sizes: [],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1756114387/products/svtuq8odg8j5pchy4a4e.jpg",
  },
  {
    id: 13,
    name: "Shirt 1",
    type: "shirt",
    buy_price: 6.8,
    sell_price: 4.5,
    discount: "18% OFF",
    stock: 0,
    status: "Out of Stock",
    sizes: [],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1756114636/products/csvxhtqpf759vupuu2k3.jpg",
  },
  {
    id: 14,
    name: "Shirt 2",
    type: "shirt",
    buy_price: 6.5,
    sell_price: 4.99,
    discount: "17% OFF",
    stock: 5,
    status: "In Stock",
    sizes: ["73", "80", "90"],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1756114439/products/ohdqtc92pzuirxdpmjlt.jpg",
  },
  {
    id: 15,
    name: "Shirt 3",
    type: "shirt",
    buy_price: 441.6,
    sell_price: 44.4,
    discount: "95% OFF",
    stock: 3,
    status: "In Stock",
    sizes: ["66", "73", "80", "90", "100"],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1756114644/products/lf7ksnqypim4cwf2lsw6.jpg",
  },
  {
    id: 16,
    name: "Shirt 4",
    type: "shirt",
    buy_price: 10.1,
    sell_price: 8.9,
    discount: "18% OFF",
    stock: 0,
    status: "Out of Stock",
    sizes: [],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1756114647/products/azuk93umgowx1pb1fetn.jpg",
  },
  {
    id: 17,
    name: "Shirt",
    type: "shirt",
    buy_price: 5.777,
    sell_price: 4.1,
    discount: "18% OFF",
    stock: 4,
    status: "In Stock",
    sizes: ["34", "67", "123"],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1758637013/products/cjaq8hu6xdjorukff0bi.jpg",
  },
  {
    id: 18,
    name: "Dress 18",
    type: "dress",
    buy_price: 6.7,
    sell_price: 4.99,
    discount: "18% OFF",
    stock: 7,
    status: "In Stock",
    sizes: ["73", "80", "90"],
    image:
      "https://res.cloudinary.com/dpcmqdi4w/image/upload/v1758612161/products/dyru5y5yddbouxv8lujg.jpg",
  },
  // ... continue same format for 19–25
];

export default products;
